spring.application.name=scamguard-ja
server.port=${PORT:8080}

gmail.redirect-uri=http://localhost:8080/auth/google/callback
gmail.scope=https://www.googleapis.com/auth/gmail.readonly

official.domains.vmbs=vmbs.com
official.domains.jnbank=jnbank.com
official.domains.ncb=jncb.com
official.domains.scotiabank=scotiabank.com
official.domains.sagicor=sagicor.com
official.domains.firstglobal=firstglobal-bank.com